### ISSUE TITLE
Duplicate hexagon

### ISSUE THREAD

**Issue by orojina** [runtastic/react-hexagon-grid#2]
Hi, first of all, thanks for this library, I find it very useful :) !

However, I'm facing the following issue:

Sometimes the react-hexagon-grid is rendering duplicate hexagons, in the image below you can see the hexagons prop of the HexagonGrid component is an array of 3 elements (3 objects). For security reasons I'm hiding the object's properties except the part of the name. 

If you look carefully you will notice that 3 hexagons are render but the last one is duplicate (position 1 of the hexagons array), the last element of the hexagons array is not render.

![image](https://user-images.githubusercontent.com/11845190/61314681-c9a46900-a7c2-11e9-84da-8a614346bc55.png)

**Comment by gvassallo** [comment]
Hi! Thanks for reporting the issue. I've just released a new version (1.1.1) which fixes the bug.

**Comment by orojina** [comment]
Thank you, seems the fix is working as expected!
